custom:
  path: /Users/jin/Downloads
  #path: /home/ubuntu/wwwroot
  key: 123456798
  salt: cms
  jwt:
    pri-key:
      path: jwt/pri.key
    pub-key:
      path: jwt/pub.key
    expiry: 120
  redis:
    prefix: cms
  upload:
    file: ${custom.path}/static/uploads/file/
    dir: ${custom.path}/static/uploads/images/
    products: ${custom.path}/static/uploads/products/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cms?useUnicode\=true&characterEncoding\=utf-8&autoReconnect\=true
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
      maximum-pool-size: 200
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
  http:
    multipart:
      location: ${custom.path}/temp
      max-file-size: 20mb
      max-request-size: 20mb
    encoding:
      force-request: true
  resources:
    static-locations: classpath:/resources,classpath:/static/,file:${custom.path}/static
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

logging:
  path: ${custom.path}/logs
  level:
    com.jieweifu: DEBUG

server:
  use-forward-headers: true
  port: 8989
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain,text/css,application/javascript,image/gif,image/jpeg,image/png